apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"labels":{"type":"local"},"name":"jenkins-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"2Gi"},"hostPath":{"path":"/mnt/nas/jenkins"},"storageClassName":"manual"}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2021-06-29T05:14:50Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    type: local
  name: jenkins-pv
  resourceVersion: "9230194"
  uid: 10fcc6dd-b3f1-48dd-8c7f-4490d9928cdf
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins-pvc
    namespace: jenkins
    resourceVersion: "9230192"
    uid: 1a9e1324-10f5-47fe-92bf-65e65da9c271
  hostPath:
    path: /mnt/nas/jenkins
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
status:
  phase: Bound
